# Basic data types

In [ ]:
import numpy as np
#Integers 
x = 3
#print the type of x
print(type(3))
# Addition : add 1 to x and print the result
print(1+x)
# Subtraction; subtract 1 from x and print the result
print(x-1)
# Multiplication; multiply x with 2 and print the result
print(x*2)
# Exponentiation; print the square of x
print(x**2)

<class 'int'>
4
2
6
9


In [ ]:
#floats
y = 2.5
#print the type of y
print(type(y))
#use operator *= to double the value of y and print y 
y*=2
print(y)


#use operator += to add 3 to y and print y 
y+=3
print(y)


<class 'float'>
5.0
8.0


In [ ]:
#Strings 
s = "hello"
# Capitalize the above string and print it
s=s.capitalize()
print(s)

#Convert the string to uppercase and print it
s=s[:].upper()
print(s)

# Right-justify the string, padding with 2 spaces print it;
s='  '+s
print(s)

# Center the string, padding with 2 spaces print it;
s=s[1:]+' '
print(s)

# Replace all instances of letter l  with "(ell)" and print it;
s=s.replace("l","ell")
print(s)
s=s.replace("L","ell")
print(s)



str = " world "
# Strip leading and trailing whitespace in the above string and print
str=str.strip()
print(str)

Hello
HELLO
  HELLO
 HELLO 
 HELLO 
 HEellellO 
world


# Containers

In [ ]:
#Lists
#create a list of first five natural numbers
list1 = [1,2,3,4]
list1.append(5)
print(list1)

#change the 3rd element to "foo" and print list1
list1[2]="foo"
print(list1)

list2 = ["bar"]
#append list2 to list1 and print the result
list1.append(list2)
print(list1)

#add list2 to list1 using extend and print the result
list1.extend(list2)
print(list1)

#remove last element in list1 using pop and print list1
list1.pop()
print(list1)


[1, 2, 3, 4, 5]
[1, 2, 'foo', 4, 5]
[1, 2, 'foo', 4, 5, ['bar']]
[1, 2, 'foo', 4, 5, ['bar'], 'bar']
[1, 2, 'foo', 4, 5, ['bar']]


In [ ]:
#Slicing 
nums = list(range(5))
#print a slice from index 2 to 4 (inclusive)
print(nums[2:5])

#print a slice from index 2 to 4 (exclusive)
print(nums[2:4])

# Slice indices can be negative; 
print(nums[:-3]) 

# Assign the [8,9] new list to a slice from index 2 to 4 (exclusive)
newlist=[8,9]
nums[2:4]=newlist
print(nums)

[2, 3, 4]
[2, 3]
[0, 1]
[0, 1, 8, 9, 4]


In [ ]:
#Loops
nums = [0, 1, 2, 3, 4]
squares = []
# append squares of each element in nums to squares using for loop
for i in nums:
  i*=i
  squares.append(i)

print(squares)
####

animals = ['cat', 'dog', 'monkey']
#print index and elements in the list using enumerate and for loop
for i in enumerate(animals):
  print(i)

#print squares of even numbers using list comprehensions
nums = [0, 1, 2, 3, 4]
even_squares = [x**2 for x in nums if x%2==0]
print(even_squares)

lst = list(enumerate(animals))
print("Just some extra practice",list(zip(*lst)))

[0, 1, 4, 9, 16]
(0, 'cat')
(1, 'dog')
(2, 'monkey')
[0, 4, 16]
Just some extra practice [(0, 1, 2), ('cat', 'dog', 'monkey')]


In [ ]:
#Dictionaries
#create a dictionary with keys = (cat, dog) and items = (cute,furry)
d = {'cat':'cute',
     'dog':'furry'}
print(d)

#set an entry {fish:wet}
d['fish']='wet'
print(d)

#remove the entry with key= cat 
d.pop('cat')
print(d)

# Get an element with a default;
print(d.get('monkey', 'N/A'))

# get an element with key= fish and print it
print(d['fish'])

#print all keys in dictionary
print(d.keys())

#print all items in dictionary
print(d.items())


{'cat': 'cute', 'dog': 'furry'}
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}
{'dog': 'furry', 'fish': 'wet'}
N/A
wet
dict_keys(['dog', 'fish'])
dict_items([('dog', 'furry'), ('fish', 'wet')])


In [ ]:
#sets 
#create a set with elements cat, dog and fish
s = {'cat','dog','fish'}
print(s)

#add monkey to the set
s.add('monkey')
print(s)

#remove fish from the set 
s.discard('fish')
print(s)

#checks if an element is in the set
print('fish' in animals)


{'cat', 'fish', 'dog'}
{'cat', 'fish', 'monkey', 'dog'}
{'cat', 'monkey', 'dog'}
False


# Numpy

In [ ]:
#importing the numpy package 
import numpy as np
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
#print the shape of the array
print(b.shape)

#print an array of all zeros of shape(2,2)
print(np.zeros((2,2)))

#print an array of all ones of shape(1,2)
print(np.ones((1,2)))

#print an array of shape (3,3) with all elements in array = 7
print(7*np.ones((3,3)))

#print an array filled with random values of shape (2,2)
print(np.random.rand(4).reshape(2,2))

(2, 3)
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]
[[0.95411714 0.65591826]
 [0.35216118 0.60749011]]


In [ ]:
import numpy as np
#ARRAY INDEXING

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Use slicing to print out the subarray consisting of the first 2 rows and columns 1 and 2;
print(a[0:2, 1:3])

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
# print one element from each row of a using the indices in b
x=0
for i in a:
  print(a[x, b[x] ])
  x+=1

# add 10 to one element from each row of a using the indices in b
x = 0
for i in a:
  a[x, b[x]]+=10
  x+=1
  
print(a)

[[2 3]
 [6 7]]
1
6
7
11
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
import numpy as np
#Boolean array indexing
a = np.array([[1,2], [3, 4], [5, 6]])
#Print a numpy array of Booleans where elements of a are bigger than 2 ,shape=(3,2)
print(a>2)

#a rank 1 array consisting of the elements of a that are bigger than 2
a=a.reshape(1,6)
print(a>2)

x = np.array([1, 2]) 
#print data type of the array
print(x.dtype)

#create an array [[1,2],[3,4]] with data type int64.
z=np.arange(1,5, dtype='int64').reshape(2,2)
print(z)

[[False False]
 [ True  True]
 [ True  True]]
[[False False  True  True  True  True]]
int64
[[1 2]
 [3 4]]


In [ ]:
#Array math
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

#print elementwise addition using numpy function
print(x+y)

#print elementwise difference using numpy function
print(x-y)

#print elementwise multiplication using numpy function
print(x*y)

#print elementwise division using numpy function
print(x/y)

#print elementwise square root using numpy function
print(x**.5)
print(y**.5)

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

#print Inner product of vectors
print(np.inner(x,y))

#print matrix / vector product of x and v 
print(np.cross(x,v))

#print matrix / vector product of x and y 
print(np.cross(x,y))


#Matrix Multiplication
print("\n\n\t Just some practice \n", x@y)

[[17 23]
 [39 53]]
[-8 -6]
[-4 -4]


	 Just some practice 
 [[19 22]
 [43 50]]


In [ ]:
x = np.array([[1,2],[3,4]])
#print sum of all elements in array
print(x.sum())

#print sum of elements in each row
print(x.sum(axis=1))

#print sum of elements in each column
print(x.sum(axis=0))




10
[3 7]
[4 6]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
#Create an empty matrix with the same shape as x and print
arr=np.empty(x.shape)
print(arr)

# create an array y by adding  the vector v to each row of the matrix x with an explicit loop 
#print y

ar=[]
for i in x:
  ar.append(i+v)
ar= np.array(ar)
print('\n',ar)


#Add v to each row of x using broadcasting
#store the result in matrix y and print y

# From the documentation, Numpy has built in broadcasting
y=x+v
print(y,"Numpy has built in broadcasting")



[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]
 [4.9e-323 5.4e-323 5.9e-323]]

 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]] Numpy has built in broadcasting


In [ ]:
import numpy as np
v = np.array([1,2,3])  
w = np.array([4,5])
#reshape v to(3,1) using numpy function and print it
v=v.reshape(3,1)
print(v)

[[1]
 [2]
 [3]]
